### ISSUE TITLE
Nativescript 6

### ISSUE THREAD

**Issue by jcarolus** [lochstar/nativescript-cast#12]
I am preparing migration of the plugin and there are a nr of breaking changes, so it's not easy to keep the plugin backward compatible for projects with older NS versions. Let me know if you are already on it, so we don't do double work @lochstar

**Comment by lochstar** [comment]
I migrated it on a local branch to test to see if the custom channels might work on Android, no dice.

Wasn't really considering backward compatibility. Figured I'd just bump the version and direct users to target an old version if they need NS5 compatibility.

**Comment by jcarolus** [comment]
ok - so no pull request needed?

**Comment by lochstar** [comment]
Only if you want to spend the time, otherwise I'll push it up when I can. Moving house next week so I'm a little busy :)

**Comment by jcarolus** [comment]
Ok, if I have some spare time in between I'll do it. Good luck with moving.
