### ISSUE TITLE
Error for Chromecast on iOS using Nativescript Angular

### ISSUE THREAD

**Issue by codecabinaustralia** [lochstar/nativescript-cast#2]
I am getting an issue on iOS, seems to be working on Android but the problem is with iOS.

I am using Nativescript Angular:

*** JavaScript call stack:
(
0 initWithFrame@[native code]
1 createnativeview@file:///app/tns_modules/nativescript-cast/cast.js:119:59
2 _setupui@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:524:47
3 @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:534:27
4 eachchildview@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34
5 eachchild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:855:27
6 _setupui@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:23
7 @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:534:27
8 eachchildview@file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:125:34
9 eachchild@file:///app/tns_modules/tns-core-modules/ui/core/view/view-common.js:855:27
10 _setupui@file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:533:23
11 @file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-ba<\M-b\M^@\M-&>
)
** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
*** First throw call stack:
(0x1e3134518 0x1e230f9f8 0x1e30adf8c 0x1e301f17c 0x101e5b258 0x101e5a404 0x101e5a2e0 0x101ad8044 0x101ad67a4 0x101ad626c 0x10118d630 0x101788e14 0x101791a24 0x101791a34 0x1017919d0 0x1017919d0 0x1017919d0 0x101791a34 0x1017919d0 0x101791a34 0x101791a34 0x1017919d0 0x1017919d0 0x101791a34 0x101791a34 0x101791a34 0x1017919d0 0x101791a34 0x1017919d0 0x1017919d0 0x1017919d0 0x101791a34 0x101791a34 0x1017919d0 0x1017919d0 0x101791a34 0x1017919d0 0x101791a34 0x101791a34 0x1017919d0 0x1017919d0 0x1017919d0 0x10178aee0 0x101724198 0x1016f9e94 0x101191f74 0x1011d4f28 0x1011d52d8 0x101ad7088 0x101ad81b4 0x20ef90014 0x20ef906e0 0x20eee7ea8 0x20eefbde8 0x20eefd210 0x20eee0420 0x20f9bbe54 0x1e75c21f0 0x1e75c7198 0x1e752a0a8 0x1e7558108 0x1e7558cf8 0x1e30c589c 0x1e30c05c4 0x1e30c0b40 0x1e30c0354 0x1e52c079c 0x20f533b68 0x101ad8044 0x101ad67a<\M-b\M^@\M-&>

Any help would be muchly appreciated.

**Comment by lochstar** [comment]
Just published `0.1.1` with Angular support and demo. Let me know if you still have this problem.
