### ISSUE TITLE
iOS 14 needs Google Cast SDK v4.5.0 

### ISSUE THREAD

**Issue by jcarolus** [lochstar/nativescript-cast#20]
According to https://developers.google.com/cast/docs/ios_sender/ios_permissions_changes#ios_14 the SDK needs to be updated to 4.5.

Let me know if you have already put efforts into this @lochstar , but I will probably create a PR once I have to address it for my projects.

**Comment by lochstar** [comment]
Thanks for pointing out the SDK update requirement.

I've created a [ns7](/lochstar/nativescript-cast/tree/ns7) branch with the work I started, feel free to pick it up.

**Comment by jcarolus** [comment]
Actually the update is only recommended when building with XCode 12; 

```Apps built with versions of the Cast SDK using v4.4.8 or earlier will continue to work as long as they are built with Xcode 11.7 or earlier. If you are building for iOS 14 with Xcode 12 or above, we recommend you update to the Cast SDK v4.5.0 to ensure that your Cast app will continue to work properly.```
