### ISSUE TITLE
Cast button won't highlight

### ISSUE THREAD

**Issue by mastashake08** [lochstar/nativescript-cast#26]
I don't know what I am doing wrong. I have a chromecast everything is on wifi but the button won't highlight blue

**Comment by sebj54** [comment]
Same here! It works well when I use a sample app ID (eg from https://github.com/googlecast/CastVideos-android/blob/master/res/values/strings.xml) but it doesn't highlight when I use a personal app ID from Google Cast Developer Console.

Have I missed something in the configuration?

**Comment by lochstar** [comment]
Double check the application status in the Google Cast Developer console. If it's unpublished you'll need to make sure your Chromecast is listed underneath. Set it to published to use it with any Chromecast.

**Comment by sebj54** [comment]
Thank you for your quick answer! 

My app is indeed unpublished but my Chromecast was listed below (and not processing). I will retry soon to see if I only had to wait a bit longer.

**EDIT:** After two days (probably less), the cast button was tapable. So I presume I had to wait longer for the app activation.
